=== mntamimi/python_dev_local/db/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/product.schema.json",
  "title": "ProductsProp",
  "description": "SAP Products",
  "type": "object",
  "properties": {
    "productId": {
      "description": "Primary Key of products table",
      "type": "integer"
    },
    "productName": {
      "description": "Name of the product",
      "type": "string"
    },
    "price": {
      "description": "The price of the product",
      "type": "number",
      "exclusiveMinimum": 0
    },
    "image": {
      "description": "Product Image",
      "type": "blob"
    },
    "description": {
      "description": "Product detail",
      "type": "string"
    },
    "required": [
      "productId",
      "productName"
    ]
  }
}

=== mntamimi/python_dev_local/db/p1.json
{
    "productId": 1,
    "productName": "S/4 HANA",
    "price": 1000,
    "image": "",
    "description": "Intelligent ERP solution that enables companies to capture every opportunity in today's digital world, SAP S/4HANA removes common obstacles associated with legacy ERP applications, such as batch latency, complex landscapes, and manually-driven processes"
  }
